# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{name:'Chicago'}, {name:'Copenhagen'}])
#   Mayor.create(name:'Emanuel', {city: cities.first)

City.create([{city_name: 'Chicago'},
             {city_name: 'Copenhagen'},
             {city_name: 'Abu Road'},
             {city_name: 'Adilabad'},
             {city_name: 'Agartala'},
             {city_name: 'Agra'},
             {city_name: 'Ahmedabad'},
             {city_name: 'Ahmednagar'},
             {city_name: 'Aizawl'},
             {city_name: 'Ajmer'},
             {city_name: 'Akola'},
             {city_name: 'Alandi'},
             {city_name: 'Alappuzha'},
             {city_name: 'Aldona'},
             {city_name: 'Alibag'},
             {city_name: 'Aligarh'},
             {city_name: 'Allahabad'},
             {city_name: 'Almora'},
             {city_name: 'Alwar'},
             {city_name: 'Amalapuram'},
             {city_name: 'Ambala'},
             {city_name: 'Amli'},
             {city_name: 'Amravati'},
             {city_name: 'Amreli'},
             {city_name: 'Amritsar'},
             {city_name: 'Anand'},
             {city_name: 'Anantapur'},
             {city_name: 'Andaman and Nicobar'},
             {city_name: 'Andhra Pradesh Others'},
             {city_name: 'Anjar'},
             {city_name: 'Ankleshwar'},
             {city_name: 'Anugul'},
             {city_name: 'Aquem'},
             {city_name: 'Ariyalur'},
             {city_name: 'Arpora'},
             {city_name: 'Arrah'},
             {city_name: 'Arunachal Pradesh Others'},
             {city_name: 'Asansol'},
             {city_name: 'Assam Others'},
             {city_name: 'Auraiya'},
             {city_name: 'Aurangabad'},
             {city_name: 'Aurangabad'},
             {city_name: 'Aurangabad'},
             {city_name: 'Azamgarh'},
             {city_name: 'Badaun'},
             {city_name: 'Baddi'},
             {city_name: 'Badgam'},
             {city_name: 'Bagalkot'},
             {city_name: 'Baghpat'},
             {city_name: 'Bagodra'},
             {city_name: 'Bahadurgarh'},
             {city_name: 'Bahal'},
             {city_name: 'Bahraich'},
             {city_name: 'Bahror'},
             {city_name: 'Balaghat'},
             {city_name: 'Balangir'},
             {city_name: 'Baleshwar'},
             {city_name: 'Balrampur'},
             {city_name: 'Baltana'},
             {city_name: 'Baltana'},
             {city_name: 'Bambolim'},
             {city_name: 'Bandora'},
             {city_name: 'Bangalore'},
             {city_name: 'Banka'},
             {city_name: 'Bankura'},
             {city_name: 'Banswara'},
             {city_name: 'Barabanki'},
             {city_name: 'Baramati'},
             {city_name: 'Baramula'},
             {city_name: 'Baran'},
             {city_name: 'Barddhaman'},
             {city_name: 'Bardoli'},
             {city_name: 'Bareilly'},
             {city_name: 'Bargarh'},
             {city_name: 'Baripada'},
             {city_name: 'Barmer'},
             {city_name: 'Barnala'},
             {city_name: 'Barpeta'},
             {city_name: 'Barwani'},
             {city_name: 'Basti'},
             {city_name: 'Batala'},
             {city_name: 'Beawar'},
             {city_name: 'Beena'},
             {city_name: 'Begusarai'},
             {city_name: 'Belgaum'},
             {city_name: 'Bellary'},
             {city_name: 'Bettiah'},
             {city_name: 'Betul'},
             {city_name: 'Bhagalpur'},
             {city_name: 'Bhandara'},
             {city_name: 'Bharatpur'},
             {city_name: 'Bharuch'},
             {city_name: 'Bhatinda'},
             {city_name: 'Bhavnagar'},
             {city_name: 'Bhilai'},
             {city_name: 'Bhilwara'},
             {city_name: 'Bhind'},
             {city_name: 'Bhiwadi'},
             {city_name: 'Bhiwandi'},
             {city_name: 'Bhiwani'},
             {city_name: 'Bhongir'},
             {city_name: 'Bhopal'},
             {city_name: 'Bhowali'},
             {city_name: 'Bhubaneshwar'},
             {city_name: 'Bhuj'},
             {city_name: 'Bicholim'},
             {city_name: 'Bid'},
             {city_name: 'Bidar'},
             {city_name: 'Bihar Others'},
             {city_name: 'Bijapur'},
             {city_name: 'Bijnor'},
             {city_name: 'Bikaner'},
             {city_name: 'Bilaspur'},
             {city_name: 'Bilimora'},
             {city_name: 'Bishnupur'},
             {city_name: 'Bokaro Steel City'},
             {city_name: 'Bolpur'},
             {city_name: 'Bongaigaon'},
             {city_name: 'Bulandshahr'},
             {city_name: 'Buldana'},
             {city_name: 'Bundi'},
             {city_name: 'Burdwan'},
             {city_name: 'Buxar'},
             {city_name: 'Calangute'},
             {city_name: 'Canacona'},
             {city_name: 'Chamba'},
             {city_name: 'Champhai'},
             {city_name: 'Chandigarh'},
             {city_name: 'Chandrapur'},
             {city_name: 'Chandwaji'},
             {city_name: 'Changlang'},
             {city_name: 'Channapatna'},
             {city_name: 'Chathanoor'},
             {city_name: 'Chatra'},
             {city_name: 'Chennai'},
             {city_name: 'Chhapra'},
             {city_name: 'Chhatarpur'},
             {city_name: 'Chhattisgarh Others'},
             {city_name: 'Chhindwara'},
             {city_name: 'Chikmagalur'},
             {city_name: 'Chintpurni'},
             {city_name: 'Chiplun'},
             {city_name: 'Chitradurga'},
             {city_name: 'Chittaurgarh'},
             {city_name: 'Chittoor'},
             {city_name: 'Churu'},
             {city_name: 'Coimbatore'},
             {city_name: 'Colachel'},
             {city_name: 'Colvale'},
             {city_name: 'Coonoor'},
             {city_name: 'Coorg'},
             {city_name: 'Cuddalore'},
             {city_name: 'Cuddapah'},
             {city_name: 'Cunningham'},
             {city_name: 'Cuttack'},
             {city_name: 'Dahanu'},
             {city_name: 'Dakshina Kannada'},
             {city_name: 'Dalhousie'},
             {city_name: 'Daman'},
             {city_name: 'Damoh'},
             {city_name: 'Dantewada'},
             {city_name: 'Dapoli'},
             {city_name: 'Darbhanga'},
             {city_name: 'Darjeeling'},
             {city_name: 'Datia'},
             {city_name: 'Dausa'},
             {city_name: 'Davanagere'},
             {city_name: 'Debagarh'},
             {city_name: 'Dehradun'},
             {city_name: 'Deoghar'},
             {city_name: 'Deoria'},
             {city_name: 'Dera Bassi'},
             {city_name: 'Dewas'},
             {city_name: 'Dhamtari'},
             {city_name: 'Dhanbad'},
             {city_name: 'Dhar'},
             {city_name: 'Dharamshala'},
             {city_name: 'Dharmapuri'},
             {city_name: 'Dharuhera'},
             {city_name: 'Dharwad'},
             {city_name: 'Dhaulpur'},
             {city_name: 'Dhemaji'},
             {city_name: 'Dhenkanal'},
             {city_name: 'Dholera'},
             {city_name: 'Dholpur'},
             {city_name: 'Dhubri'},
             {city_name: 'Dhule'},
             {city_name: 'Dibrugarh'},
             {city_name: 'Dimapur'},
             {city_name: 'Dindigul'},
             {city_name: 'Dindori'},
             {city_name: 'Diphu'},
             {city_name: 'Diu'},
             {city_name: 'Doda'},
             {city_name: 'Dohad'},
             {city_name: 'Dumka'},
             {city_name: 'Dungarpur'},
             {city_name: 'Durg'},
             {city_name: 'Durgapur'},
             {city_name: 'Dwarka'},
             {city_name: 'East Godavari'},
             {city_name: 'Ernakulam'},
             {city_name: 'Erode'},
             {city_name: 'Etah'},
             {city_name: 'Etawah'},
             {city_name: 'Faizabad'},
             {city_name: 'Faridabad'},
             {city_name: 'Faridkot'},
             {city_name: 'Farrukhabad'},
             {city_name: 'Fatehabad'},
             {city_name: 'Fatehabad'},
             {city_name: 'Fazilka'},
             {city_name: 'Firozabad'},
             {city_name: 'Firozpur'},
             {city_name: 'Gadchiroli'},
             {city_name: 'Gadhada'},
             {city_name: 'Gajraula'},
             {city_name: 'Gandhidham'},
             {city_name: 'Gandhinagar'},
             {city_name: 'Ganganagar'},
             {city_name: 'Gangtok'},
             {city_name: 'Ganjam'},
             {city_name: 'Garhwa'},
             {city_name: 'Garhwal'},
             {city_name: 'Gaya'},
             {city_name: 'Ghaziabad'},
             {city_name: 'Ghazipur'},
             {city_name: 'Gir'},
             {city_name: 'Giridih'},
             {city_name: 'Goa'},
             {city_name: 'Goa Others'},
             {city_name: 'Goalpara'},
             {city_name: 'GOA-Madgaon'},
             {city_name: 'GOA-Panaji'},
             {city_name: 'Godda'},
             {city_name: 'Golaghat'},
             {city_name: 'Gonda'},
             {city_name: 'Gondiya'},
             {city_name: 'Gopalganj'},
             {city_name: 'Gorakhpur'},
             {city_name: 'Greater Noida'},
             {city_name: 'Gujarat Others'},
             {city_name: 'Gulbarga'},
             {city_name: 'Guna'},
             {city_name: 'Guntakal'},
             {city_name: 'Guntur'},
             {city_name: 'Gurdaspur'},
             {city_name: 'Gurgaon'},
             {city_name: 'Guruvayoor'},
             {city_name: 'Guwahati'},
             {city_name: 'Gwalior'},
             {city_name: 'Hailakandi'},
             {city_name: 'Haldia'},
             {city_name: 'Haldwani'},
             {city_name: 'Hamirpur'},
             {city_name: 'Hamirpur'},
             {city_name: 'Hansi'},
             {city_name: 'Hanumangarh'},
             {city_name: 'Hapur'},
             {city_name: 'Harda'},
             {city_name: 'Hardoi'},
             {city_name: 'Haridwar'},
             {city_name: 'Harihareshwar'},
             {city_name: 'Haryana Others'},
             {city_name: 'Hassan'},
             {city_name: 'Hathras'},
             {city_name: 'Haveri'},
             {city_name: 'Hazaribag'},
             {city_name: 'Himachal Pradesh Others'},
             {city_name: 'Himatnagar'},
             {city_name: 'Hingoli'},
             {city_name: 'Hisar'},
             {city_name: 'Hoogly'},
             {city_name: 'Hoshangabad'},
             {city_name: 'Hoshiarpur'},
             {city_name: 'Hosur'},
             {city_name: 'Howrah'},
             {city_name: 'Hubli-Dharwad'},
             {city_name: 'Hyderabad'},
             {city_name: 'Idar'},
             {city_name: 'Idigarai'},
             {city_name: 'Idukki'},
             {city_name: 'Imphal'},
             {city_name: 'Indore'},
             {city_name: 'Itanagar'},
             {city_name: 'Jabalpur'},
             {city_name: 'Jagadhri'},
             {city_name: 'Jagatsinghapur'},
             {city_name: 'Jagdalpur'},
             {city_name: 'Jaipur'},
             {city_name: 'Jaisalmer'},
             {city_name: 'Jajapur'},
             {city_name: 'Jalandhar'},
             {city_name: 'Jalaun'},
             {city_name: 'Jalgaon'},
             {city_name: 'Jalna'},
             {city_name: 'Jalor'},
             {city_name: 'Jalpaiguri'},
             {city_name: 'Jammu'},
             {city_name: 'Jammu and Kashmir Others'},
             {city_name: 'Jamnagar'},
             {city_name: 'Jamshedpur'},
             {city_name: 'Jamui'},
             {city_name: 'Jasidih'},
             {city_name: 'Jaunpur'},
             {city_name: 'Jehanabad'},
             {city_name: 'Jhabua'},
             {city_name: 'Jhajjar'},
             {city_name: 'Jhalawar'},
             {city_name: 'Jhansi'},
             {city_name: 'Jharkhand Others'},
             {city_name: 'Jharsuguda'},
             {city_name: 'Jhunjhunun'},
             {city_name: 'Jind'},
             {city_name: 'Jodhpur'},
             {city_name: 'Jorhat'},
             {city_name: 'Junagadh'},
             {city_name: 'Junnar'},
             {city_name: 'Kaithal'},
             {city_name: 'Kakinada'},
             {city_name: 'Kalka'},
             {city_name: 'Kalol'},
             {city_name: 'Kalpakkam'},
             {city_name: 'Kalyani'},
             {city_name: 'Kancheepuram'},
             {city_name: 'Kangra'},
             {city_name: 'Kanker'},
             {city_name: 'Kannauj'},
             {city_name: 'Kanniyakumari'},
             {city_name: 'Kannur'},
             {city_name: 'Kanpur'},
             {city_name: 'Kansal'},
             {city_name: 'Kansal'},
             {city_name: 'Kapurthala'},
             {city_name: 'Karaikal'},
             {city_name: 'Karauli'},
             {city_name: 'Kargil'},
             {city_name: 'Karimganj'},
             {city_name: 'Karimnagar'},
             {city_name: 'Karjat'},
             {city_name: 'Karnal'},
             {city_name: 'Karnataka Others'},
             {city_name: 'Karur'},
             {city_name: 'Karwar'},
             {city_name: 'Kasaragod'},
             {city_name: 'Kasauli'},
             {city_name: 'Kashipur'},
             {city_name: 'Kathua'},
             {city_name: 'Katihar'},
             {city_name: 'Katni'},
             {city_name: 'Katrain'},
             {city_name: 'Kavaratti'},
             {city_name: 'Kawardha'},
             {city_name: 'Kayamkulam'},
             {city_name: 'Kendrapara'},
             {city_name: 'Kendujhar'},
             {city_name: 'Kerala Others'},
             {city_name: 'Khagaria'},
             {city_name: 'Khajuraho'},
             {city_name: 'Khammam'},
             {city_name: 'Khandala'},
             {city_name: 'Khanna'},
             {city_name: 'Kharagpur'},
             {city_name: 'Khardi'},
             {city_name: 'Khargone'},
             {city_name: 'Khatauli'},
             {city_name: 'Kheda'},
             {city_name: 'Khedbrahma'},
             {city_name: 'Kheri'},
             {city_name: 'Khordha'},
             {city_name: 'Kishanganj'},
             {city_name: 'Koch Bihar'},
             {city_name: 'Kochi'},
             {city_name: 'Kodaikanal'},
             {city_name: 'Kodarma'},
             {city_name: 'Kohima'},
             {city_name: 'Kokrajhar'},
             {city_name: 'Kolar'},
             {city_name: 'Kolasib'},
             {city_name: 'Kolhapur'},
             {city_name: 'Kolkata'},
             {city_name: 'Kolkhe'},
             {city_name: 'Kollam'},
             {city_name: 'Koppal'},
             {city_name: 'Koraput'},
             {city_name: 'Korba'},
             {city_name: 'Kota'},
             {city_name: 'Kota'},
             {city_name: 'Kotdwar'},
             {city_name: 'Koteshwar'},
             {city_name: 'Kottakudi'},
             {city_name: 'Kottayam'},
             {city_name: 'Kovur'},
             {city_name: 'Kozhikode'},
             {city_name: 'Krishnagiri'},
             {city_name: 'Krishnanagar'},
             {city_name: 'Kudal'},
             {city_name: 'Kufri'},
             {city_name: 'Kullu'},
             {city_name: 'Kumhari'},
             {city_name: 'Kupwara'},
             {city_name: 'Kurnool'},
             {city_name: 'Kurukshetra'},
             {city_name: 'Kushinagar'},
             {city_name: 'Kutch'},
             {city_name: 'Lakhisarai'},
             {city_name: 'Lalitpur'},
             {city_name: 'Lansdowne'},
             {city_name: 'Latur'},
             {city_name: 'Lavasa'},
             {city_name: 'Leh'},
             {city_name: 'Lohardaga'},
             {city_name: 'Lonavala'},
             {city_name: 'Lucknow'},
             {city_name: 'Ludhiana'},
             {city_name: 'Lunglei'},
             {city_name: 'Madhepura'},
             {city_name: 'Madhubani'},
             {city_name: 'Madhya Pradesh Others'},
             {city_name: 'Madikeri'},
             {city_name: 'Madurai'},
             {city_name: 'Mahabaleshwar'},
             {city_name: 'Maharashtra Others'},
             {city_name: 'Mahasamund'},
             {city_name: 'Mahbubnagar'},
             {city_name: 'Mahe'},
             {city_name: 'Mahendragarh'},
             {city_name: 'Mahesana'},
             {city_name: 'Mahoba'},
             {city_name: 'Mahona'},
             {city_name: 'Mainpuri'},
             {city_name: 'Malappuram'},
             {city_name: 'Malda'},
             {city_name: 'Mamallapuram'},
             {city_name: 'Mamit'},
             {city_name: 'Manali'},
             {city_name: 'Mandawa'},
             {city_name: 'Mandi'},
             {city_name: 'Mandla'},
             {city_name: 'Mandsaur'},
             {city_name: 'Mandya'},
             {city_name: 'Mangalore'},
             {city_name: 'Manipal'},
             {city_name: 'Manipur Others'},
             {city_name: 'Mansa'},
             {city_name: 'Mapusa'},
             {city_name: 'Margao'},
             {city_name: 'Marigaon'},
             {city_name: 'Maroli'},
             {city_name: 'Mathura'},
             {city_name: 'Matli'},
             {city_name: 'Medak'},
             {city_name: 'Medininagar (Daltonganj)'},
             {city_name: 'Medinipur'},
             {city_name: 'Meerut'},
             {city_name: 'Meghalaya Others'},
             {city_name: 'Mizoram Others'},
             {city_name: 'Moga'},
             {city_name: 'Mohali'},
             {city_name: 'Mokokchung'},
             {city_name: 'Moradabad'},
             {city_name: 'Morbi'},
             {city_name: 'Morena'},
             {city_name: 'Mormugao'},
             {city_name: 'Motera'},
             {city_name: 'Motihari'},
             {city_name: 'Mount Abu'},
             {city_name: 'Muktsar'},
             {city_name: 'Mumbai'},
             {city_name: 'Munger'},
             {city_name: 'Munnar'},
             {city_name: 'Murbad'},
             {city_name: 'Murshidabad'},
             {city_name: 'Mussoorie'},
             {city_name: 'Muzaffarnagar'},
             {city_name: 'Muzaffarpur'},
             {city_name: 'Mysore'},
             {city_name: 'Nabarangapur'},
             {city_name: 'Nagaland Others'},
             {city_name: 'Nagaon'},
             {city_name: 'Nagapattinam'},
             {city_name: 'Nagaur'},
             {city_name: 'Nagercoil'},
             {city_name: 'Nagpur'},
             {city_name: 'Nainital'},
             {city_name: 'Nalbari'},
             {city_name: 'Nalgonda'},
             {city_name: 'Namakkal'},
             {city_name: 'Nanded'},
             {city_name: 'Nandurbar'},
             {city_name: 'Naraina'},
             {city_name: 'Narayangaon'},
             {city_name: 'Narnaul'},
             {city_name: 'Narsimhapur'},
             {city_name: 'Narwana'},
             {city_name: 'Nashik'},
             {city_name: 'Navi Mumbai'},
             {city_name: 'Navsari'},
             {city_name: 'Nawada'},
             {city_name: 'Nawalgarh'},
             {city_name: 'Nawanshahr'},
             {city_name: 'Nayagarh'},
             {city_name: 'Neemrana'},
             {city_name: 'Neemuch'},
             {city_name: 'Nellore'},
             {city_name: 'New Delhi'},
             {city_name: 'Nizamabad'},
             {city_name: 'Noida'},
             {city_name: 'North Goa'},
             {city_name: 'Okkiyam Thuraipakkam'},
             {city_name: 'Ongole'},
             {city_name: 'Ooty'},
             {city_name: 'Oragadam'},
             {city_name: 'Orchha'},
             {city_name: 'Orissa Others'},
             {city_name: 'Osmanabad'},
             {city_name: 'Others (Delhi)'},
             {city_name: 'Pakaur'},
             {city_name: 'Palakkad'},
             {city_name: 'Palani'},
             {city_name: 'Palanpur'},
             {city_name: 'Palghar'},
             {city_name: 'Pali'},
             {city_name: 'Palwal'},
             {city_name: 'Panchkula'},
             {city_name: 'Panipat'},
             {city_name: 'Panna'},
             {city_name: 'Panoli'},
             {city_name: 'Parbhani'},
             {city_name: 'Parwanoo'},
             {city_name: 'Patan'},
             {city_name: 'Pathanamthitta'},
             {city_name: 'Pathankot'},
             {city_name: 'Patiala'},
             {city_name: 'Patna'},
             {city_name: 'Perambalur'},
             {city_name: 'Pernem Taluka'},
             {city_name: 'Phek'},
             {city_name: 'Phulera'},
             {city_name: 'Pilibhit'},
             {city_name: 'Pimpri Chinchwad'},
             {city_name: 'Pinjore'},
             {city_name: 'Pithoragarh'},
             {city_name: 'Pollachi'},
             {city_name: 'Ponda'},
             {city_name: 'Pondicherry'},
             {city_name: 'Poonamallee'},
             {city_name: 'Porbandar'},
             {city_name: 'Port Blair'},
             {city_name: 'Prakasam'},
             {city_name: 'Pudukkottai'},
             {city_name: 'Pune'},
             {city_name: 'Punjab Others'},
             {city_name: 'Puri'},
             {city_name: 'Purnia'},
             {city_name: 'Puruliya'},
             {city_name: 'Pushkar'},
             {city_name: 'Puttur'},
             {city_name: 'Rae Bareli'},
             {city_name: 'Raichur'},
             {city_name: 'Raigad'},
             {city_name: 'Raigarh'},
             {city_name: 'Raipur'},
             {city_name: 'Raisen'},
             {city_name: 'Rajahmundry'},
             {city_name: 'Rajapur'},
             {city_name: 'Rajasthan Others'},
             {city_name: 'Rajauri'},
             {city_name: 'Rajgarh'},
             {city_name: 'Rajgarh'},
             {city_name: 'Rajkot'},
             {city_name: 'Rajnandgaon'},
             {city_name: 'Rajpura'},
             {city_name: 'Rajsamand'},
             {city_name: 'Ramanagara'},
             {city_name: 'Ramanathapuram'},
             {city_name: 'Ramgarh'},
             {city_name: 'Rampur'},
             {city_name: 'Rampur'},
             {city_name: 'Ranchi'},
             {city_name: 'Rangia'},
             {city_name: 'Raniganj'},
             {city_name: 'Ranikhet'},
             {city_name: 'Ranipet'},
             {city_name: 'Ratlam'},
             {city_name: 'Ratnagiri'},
             {city_name: 'Raulapalem'},
             {city_name: 'Raurkela'},
             {city_name: 'Rayagada'},
             {city_name: 'Rewa'},
             {city_name: 'Rewari'},
             {city_name: 'Rishikesh'},
             {city_name: 'Rishra'},
             {city_name: 'Roha'},
             {city_name: 'Rohtak'},
             {city_name: 'Roorkee'},
             {city_name: 'Ropar/Rupnager'},
             {city_name: 'Rudrapur'},
             {city_name: 'Sabarkantha'},
             {city_name: 'Sagar'},
             {city_name: 'Saharanpur'},
             {city_name: 'Saharsa'},
             {city_name: 'Sahibganj'},
             {city_name: 'Saiha'},
             {city_name: 'Salem'},
             {city_name: 'Samastipur'},
             {city_name: 'Sambalpur'},
             {city_name: 'Sambhar'},
             {city_name: 'Sanand'},
             {city_name: 'Sancoale'},
             {city_name: 'Sangli'},
             {city_name: 'Sangrur'},
             {city_name: 'Satara'},
             {city_name: 'Satna'},
             {city_name: 'Sawai Madhopur'},
             {city_name: 'Secunderabad'},
             {city_name: 'Sehore'},
             {city_name: 'Seoni'},
             {city_name: 'Serchhip'},
             {city_name: 'Shahjahanpur'},
             {city_name: 'Shantiniketan'},
             {city_name: 'Shikohabad'},
             {city_name: 'Shillong'},
             {city_name: 'Shimla'},
             {city_name: 'Shimoga'},
             {city_name: 'Shirdi'},
             {city_name: 'Shivpuri'},
             {city_name: 'Shrivardhan'},
             {city_name: 'Sibsagar'},
             {city_name: 'Sidhi'},
             {city_name: 'Sikar'},
             {city_name: 'Sikkim Others'},
             {city_name: 'Silchar'},
             {city_name: 'Siliguri'},
             {city_name: 'Silvassa'},
             {city_name: 'Sindhudurg'},
             {city_name: 'Sirohi'},
             {city_name: 'Sirsa'},
             {city_name: 'Sitamarhi'},
             {city_name: 'Sitapur'},
             {city_name: 'Sivaganga'},
             {city_name: 'Sivakasi'},
             {city_name: 'Solan'},
             {city_name: 'Solapur'},
             {city_name: 'Somvarpet'},
             {city_name: 'Sonipat'},
             {city_name: 'South Goa'},
             {city_name: 'Srikakulam'},
             {city_name: 'Srinagar'},
             {city_name: 'Srinagar'},
             {city_name: 'Sriperumbudur'},
             {city_name: 'Subrahmanya'},
             {city_name: 'Sultanpur'},
             {city_name: 'Sundargarh'},
             {city_name: 'Surat'},
             {city_name: 'Surendranagar'},
             {city_name: 'Talod'},
             {city_name: 'Tamil Nadu Others'},
             {city_name: 'Tawang'},
             {city_name: 'Tenali'},
             {city_name: 'Tezpur'},
             {city_name: 'Thane'},
             {city_name: 'Thanjavur'},
             {city_name: 'Theni'},
             {city_name: 'Thiruvallur'},
             {city_name: 'Thiruvananthapuram'},
             {city_name: 'Thiruvarur'},
             {city_name: 'Thoubal'},
             {city_name: 'Thrissur'},
             {city_name: 'Tikamgarh'},
             {city_name: 'Tinsukia'},
             {city_name: 'Tiruchirappalli'},
             {city_name: 'Tirunelveli'},
             {city_name: 'Tirupathi'},
             {city_name: 'Tirupattur'},
             {city_name: 'Tiruppur'},
             {city_name: 'Tirur'},
             {city_name: 'Tiruvannamalai'},
             {city_name: 'Tonk'},
             {city_name: 'Tripura Others'},
             {city_name: 'Trivandrum'},
             {city_name: 'Tuensang'},
             {city_name: 'Tumkur'},
             {city_name: 'Tuticorin'},
             {city_name: 'Udaipur'},
             {city_name: 'Udaipur'},
             {city_name: 'Udhampur'},
             {city_name: 'Udupi'},
             {city_name: 'Ujjain'},
             {city_name: 'Umaria'},
             {city_name: 'Una'},
             {city_name: 'Unnao'},
             {city_name: 'Uttar Pradesh Others'},
             {city_name: 'Uttarakhand Others'},
             {city_name: 'Uttarkashi'},
             {city_name: 'Vadali'},
             {city_name: 'Vadodara'},
             {city_name: 'Valsad'},
             {city_name: 'Vapi'},
             {city_name: 'Varanasi'},
             {city_name: 'Varca'},
             {city_name: 'Vasai'},
             {city_name: 'Vasco Da Gama'},
             {city_name: 'Vellore'},
             {city_name: 'Vidisha'},
             {city_name: 'Vijayawada'},
             {city_name: 'Vikarabad'},
             {city_name: 'Viluppuram'},
             {city_name: 'Viramgam'},
             {city_name: 'Virar'},
             {city_name: 'Virudhunagar'},
             {city_name: 'Vishakhapatnam'},
             {city_name: 'Vizianagaram'},
             {city_name: 'Vrindavan'},
             {city_name: 'Vyara'},
             {city_name: 'Warangal'},
             {city_name: 'Wardha'},
             {city_name: 'Wargal'},
             {city_name: 'Washim'},
             {city_name: 'Wayanad'},
             {city_name: 'West Bengal Others'},
             {city_name: 'Wokha'},
             {city_name: 'Yamunanagar'},
             {city_name: 'Yanam'},
             {city_name: 'Yavatmal'},
             {city_name: 'Zirakhpur'},
             {city_name: 'Zunheboto'}])

Type.create([{property_type: 'Builder Floor Apartment'},
             {property_type: 'Holiday Home'},
             {property_type: 'Multistorey Apartment'},
             {property_type: 'Other-Residential'},
             {property_type: 'Penthouse'},
             {property_type: 'Residential House'},
             {property_type: 'Residential Mansion'},
             {property_type: 'Residential Plot'},
             {property_type: 'Service Apartment'},
             {property_type: 'Service Studio Apartments'},
             {property_type: 'Studio Apartment'},
             {property_type: 'Villa'},
             {property_type: 'Banquet Hall'},
             {property_type: 'Business Centre'},
             {property_type: 'Business Suite'},
             {property_type: 'Cold Storage'},
             {property_type: 'Commercial Land'},
             {property_type: 'Commercial Mansion'},
             {property_type: 'Commercial Office Space'},
             {property_type: 'Commercial Shop'},
             {property_type: 'Commercial Showroom'},
             {property_type: 'Factory'},
             {property_type: 'Guest House'},
             {property_type: 'Hotel'},
             {property_type: 'Hotel Sites'},
             {property_type: 'Industrial Building'},
             {property_type: 'Industrial Land'},
             {property_type: 'Industrial Shed'},
             {property_type: 'IT Studio Apartment'},
             {property_type: 'Kiosk'},
             {property_type: 'Manufacturing'},
             {property_type: 'Office in Business Park'},
             {property_type: 'Office in IT Park/SEZ'},
             {property_type: 'Other-Commercial'},
             {property_type: 'Resort'},
             {property_type: 'Space in Retail Mall'},
             {property_type: 'Time Share'},
             {property_type: 'Warehouse/Godown'},
             {property_type: 'Agricultural Land'},
             {property_type: 'Farm House'}])

Promo.create([{promo_heading: '2, 3 BHK Multistorey Apartment', promo_content: 'Rs. 4799/- per Sq-ft', promo_extra_content: 'Sector-76, Noida', promo_number: '9818944944', promo_priority: 1},
              {promo_heading: '2, 3 BHK Multistorey Apartment', promo_content: 'Rs. 4799/- per Sq-ft', promo_extra_content: 'Sector-76, Noida', promo_number: '9818944944', promo_priority: 2},
              {promo_heading: '2, 3 BHK Multistorey Apartment', promo_content: 'Rs. 4799/- per Sq-ft', promo_extra_content: 'Sector-76, Noida', promo_number: '9818944944', promo_priority: 3},
              {promo_heading: '2, 3 BHK Multistorey Apartment', promo_content: 'Rs. 4799/- per Sq-ft', promo_extra_content: 'Sector-76, Noida', promo_number: '9818944944', promo_priority: 2},
              {promo_heading: '2, 3 BHK Multistorey Apartment', promo_content: 'Rs. 4799/- per Sq-ft', promo_extra_content: 'Sector-76, Noida', promo_number: '9818944944', promo_priority: 1},
              {promo_heading: '2, 3 BHK Multistorey Apartment', promo_content: 'Rs. 4799/- per Sq-ft', promo_extra_content: 'Sector-76, Noida', promo_number: '9818944944', promo_priority: 2},
              {promo_heading: '2, 3 BHK Multistorey Apartment', promo_content: 'Rs. 4799/- per Sq-ft', promo_extra_content: 'Sector-76, Noida', promo_number: '9818944944', promo_priority: 3},
              {promo_heading: '2, 3 BHK Multistorey Apartment', promo_content: 'Rs. 4799/- per Sq-ft', promo_extra_content: 'Sector-76, Noida', promo_number: '9818944944', promo_priority: 2},
              {promo_heading: '2, 3 BHK Multistorey Apartment', promo_content: 'Rs. 4799/- per Sq-ft', promo_extra_content: 'Sector-76, Noida', promo_number: '9818944944', promo_priority: 1},
              {promo_heading: '2, 3 BHK Multistorey Apartment', promo_content: 'Rs. 4799/- per Sq-ft', promo_extra_content: 'Sector-76, Noida', promo_number: '9818944944', promo_priority: 2}
             ])